const configHash = "local fixture generated by scripts/export-evidence.js";

document.querySelector("#configHash").textContent = configHash;
document.querySelector("#claimButton").addEventListener("click", () => {
  document.querySelector("#claimOutput").textContent = "Preview only: claim requires a Shipped user and signer-owned token account.";
});
